// =====================================================================
// CMS Exporter — turns a CMS draft into platform-ready course files
// and bundles them as a ZIP. Drop the contents into the repo, add the
// registry entry + vite input (both included in INSTALL.md) — done.
// =====================================================================
import JSZip from 'jszip'
import { renderSlideContent } from './templates.js'

const slug = (s) => (s || 'kurs').toLowerCase()
  .replaceAll('ä', 'ae').replaceAll('ö', 'oe').replaceAll('ü', 'ue').replaceAll('ß', 'ss')
  .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'kurs'

const camel = (s) => slug(s).replace(/-(\w)/g, (_, c) => c.toUpperCase())

function slideToSource(slide) {
  const props = []
  props.push(`    id: ${JSON.stringify(slide.id)}`)
  props.push(`    theme: ${JSON.stringify(slide.theme || '')}`)
  props.push(`    label: ${JSON.stringify(slide.label || slide.id)}`)
  if (slide.quiz) props.push('    quiz: true')
  if (slide.desktopOnly) props.push('    desktopOnly: true')
  if (slide.mobileOnly) props.push('    mobileOnly: true')
  if (slide.selfPacedOnly) props.push('    selfPacedOnly: true')
  // content as JSON string -> no backtick/interpolation escaping issues
  props.push(`    content: ${JSON.stringify(renderSlideContent(slide))}`)
  return `  {\n${props.join(',\n')},\n  },`
}

export function generateCourseFiles(course) {
  const id = slug(course.id || course.title)
  const lang = course.lang || 'de'
  const files = {}

  // --- section files ---
  const sectionImports = []
  const sectionVars = []
  course.sections.forEach((sec, i) => {
    const num = String(i + 1).padStart(2, '0')
    const varName = `${camel(sec.name) || 'section' + num}Slides`
    const fileName = `${num}-${slug(sec.name)}.js`
    sectionImports.push(`import { ${varName} } from './sections/${lang}/${fileName}'`)
    sectionVars.push(varName)
    files[`src/courses/${id}/sections/${lang}/${fileName}`] =
      `export const ${varName} = [\n${sec.slides.map(slideToSource).join('\n')}\n];\n`
  })

  // --- course.js ---
  const sectionDefs = course.sections.map((sec, i) =>
    `    { start: ${JSON.stringify(sec.slides[0]?.id || '')}, nameIdx: ${i} },`).join('\n')
  files[`src/courses/${id}/course.js`] = `// Generated by Kurs-Studio (CMS) — ${new Date().toISOString().slice(0, 10)}
import { initCourse } from '../../engine/engine.js'

${sectionImports.join('\n')}

initCourse({
  id: ${JSON.stringify(id)},
  version: ${JSON.stringify(course.version || '1.0.0')},
  defaultLang: ${JSON.stringify(lang)},
  slides: {
    ${lang}: [${sectionVars.join(', ')}],
  },
  sectionNames: {
    ${lang}: [${course.sections.map(s => JSON.stringify(s.name)).join(', ')}],
  },
  sections: [
${sectionDefs}
  ],
  meta: {
    ${lang}: {
      title: ${JSON.stringify(course.title)},
      description: ${JSON.stringify(course.description || '')},
    },
  },
})
`

  // --- index.html ---
  files[`courses/${id}/index.html`] = `<!doctype html>
<html lang="${lang}">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${course.title}</title>
    <meta name="description" content="${(course.description || '').replaceAll('"', '&quot;')}" />
    <meta property="og:title" content="${course.title}" />
    <meta property="og:description" content="${(course.description || '').replaceAll('"', '&quot;')}" />
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/courses/${id}/course.js"></script>
  </body>
</html>
`

  // --- INSTALL.md ---
  files['INSTALL.md'] = `# Kurs installieren: ${course.title}

1. **Dateien kopieren** — die Ordner \`courses/\` und \`src/\` aus diesem ZIP ins Projekt-Root kopieren (Struktur bleibt erhalten).

2. **Registry-Eintrag** — in \`src/courses-registry.js\` ergänzen:

\`\`\`js
{
  id: '${id}',
  path: '/courses/${id}/',
  emoji: '${course.emoji || '📚'}',
  languages: ['${lang}'],
  duration: '${course.duration || '~45min'}',
  level: { ${lang}: '${course.level || 'Alle'}' },
  title: { ${lang}: ${JSON.stringify(course.title)} },
  description: { ${lang}: ${JSON.stringify(course.description || '')} },
  tags: ${JSON.stringify(course.tags || [])},
},
\`\`\`

3. **Vite-Input** — in \`vite.config.js\` unter \`rollupOptions.input\` ergänzen:

\`\`\`js
${camel(id)}: resolve(__dirname, 'courses/${id}/index.html'),
\`\`\`

4. \`npm run dev\` — der Kurs läuft unter \`/courses/${id}/\`.

Tipp: Die generierten Section-Dateien sind normaler Code — du kannst sie danach
beliebig von Hand (oder per AI-Agent) verfeinern.
`

  return { id, files }
}

export async function exportZip(course) {
  const { id, files } = generateCourseFiles(course)
  const zip = new JSZip()
  Object.entries(files).forEach(([path, content]) => zip.file(path, content))
  const blob = await zip.generateAsync({ type: 'blob' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `kurs-${id}.zip`
  a.click()
  URL.revokeObjectURL(a.href)
}
